import { StyleSheet } from "react-native";
import { DesignSystem } from "../../../theme/designSystem";
import { colors } from "src/theme/colors";

export const timelineStyles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: DesignSystem.spacing.lg,
  },
  header: {
    paddingHorizontal: DesignSystem.spacing.md,
    marginBottom: DesignSystem.spacing.md,
  },
  title: {
    ...DesignSystem.typography.h2,
    color: colors.light.text,
  },
  subtitle: {
    ...DesignSystem.typography.body,
    color: colors.light.textSecondary,
    marginTop: DesignSystem.spacing.xs,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: DesignSystem.spacing.xxl,
  },
  dateGroup: {
    marginBottom: DesignSystem.spacing.xl,
  },
  dateHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: DesignSystem.spacing.md,
    marginBottom: DesignSystem.spacing.md,
  },
  dateIndicator: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.light.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: DesignSystem.spacing.md,
    ...DesignSystem.shadows.small,
  },
  dateNumber: {
    ...DesignSystem.typography.h4,
    color: colors.light.surface,
    fontWeight: "700",
  },
  dateMonth: {
    ...DesignSystem.typography.caption,
    color: colors.light.surface,
    fontWeight: "600",
  },
  dateInfo: {
    flex: 1,
  },
  dateText: {
    ...DesignSystem.typography.bodySemiBold,
    color: colors.light.text,
  },
  taskCount: {
    ...DesignSystem.typography.small,
    color: colors.light.textSecondary,
    marginTop: 2,
  },
  taskItem: {
    flexDirection: "row",
    paddingHorizontal: DesignSystem.spacing.md,
    marginBottom: DesignSystem.spacing.sm,
  },
  lastTaskItem: {
    marginBottom: 0,
  },
  timelineLine: {
    width: 50,
    alignItems: "center",
    marginRight: DesignSystem.spacing.md,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.light.primary,
    borderWidth: 2,
    borderColor: colors.light.surface,
    ...DesignSystem.shadows.small,
  },
  timelineConnector: {
    width: 2,
    height: 40,
    backgroundColor: colors.light.border,
    marginTop: DesignSystem.spacing.xs,
  },
  taskContent: {
    flex: 1,
    backgroundColor: colors.light.surface,
    borderRadius: DesignSystem.borders.radius.medium,
    padding: DesignSystem.spacing.md,
    ...DesignSystem.shadows.small,
  },
  taskHeader: {
    marginBottom: DesignSystem.spacing.sm,
  },
  taskTitle: {
    ...DesignSystem.typography.bodySemiBold,
    color: colors.light.text,
    marginBottom: DesignSystem.spacing.xs,
  },
  taskMeta: {
    flexDirection: "row",
    gap: DesignSystem.spacing.sm,
  },
  priorityBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.light.background,
    paddingHorizontal: DesignSystem.spacing.sm,
    paddingVertical: 4,
    borderRadius: DesignSystem.borders.radius.small,
  },
  priorityDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: DesignSystem.spacing.xs,
  },
  priorityText: {
    ...DesignSystem.typography.caption,
    color: colors.light.textSecondary,
    textTransform: "capitalize",
  },
  durationBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.light.background,
    paddingHorizontal: DesignSystem.spacing.sm,
    paddingVertical: 4,
    borderRadius: DesignSystem.borders.radius.small,
  },
  durationText: {
    ...DesignSystem.typography.caption,
    color: colors.light.textSecondary,
    marginLeft: DesignSystem.spacing.xs,
  },
  taskFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  taskTime: {
    ...DesignSystem.typography.small,
    color: colors.light.textSecondary,
  },
  completeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyContainer: {
    height: 180,
    marginVertical: DesignSystem.spacing.lg,
    marginHorizontal: DesignSystem.spacing.md,
    borderRadius: DesignSystem.borders.radius.large,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: DesignSystem.spacing.xl,
    paddingHorizontal: DesignSystem.spacing.lg,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: DesignSystem.spacing.lg,
  },
  emptyIconBackground: {
    flex: 1,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyTitle: {
    ...DesignSystem.typography.h3,
    marginBottom: DesignSystem.spacing.sm,
    textAlign: "center",
    fontWeight: "700",
  },
  emptySubtitle: {
    ...DesignSystem.typography.body,
    textAlign: "center",
    opacity: 0.8,
  },
});
